In [1]:
import os
import gzip
import errno
import shutil
import pydicom
import numpy as np
import collections

from PIL import Image
import nibabel as nib

import tifffile as tiff
# from tifffile import imsave
import imageio

import matplotlib.pyplot as plt

from skimage.transform import resize
from torch.utils import data
#
import torch
import random
import numpy as np
import os
import torch.nn as nn
import glob
import tifffile as tiff
import torch.nn.functional as F
# ===================================
from NNUtils import CustomDataset_OCT

/home/moucheng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/moucheng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/moucheng/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/moucheng/anaconda3/lib/python3.7/site-packages/tensorflow/python/frame

In [2]:
data_direcotry = '/home/moucheng/projects_data/OCT/duke_dataset/backup/'
# =======================================================

train_image_folder = data_direcotry + 'all/' + 'images'
train_label_folder = data_direcotry + 'all/' + 'masks'
#
train_dataset = CustomDataset_OCT(train_image_folder, train_label_folder, teacher_student=False, transforms='none')

print(len(train_dataset))

# print(train_dataset)

# trainloader = data.DataLoader(train_dataset, batch_size=2, shuffle=True, num_workers=2, drop_last=False)
# index = 2
# #
# image, label, label_name = train_dataset[index]
#

48


In [3]:
# print(image.shape)
# print(label.shape)

# plt.imshow(image[0, :, :], cmap='gray')
# plt.show()

# plt.imshow(label[0, :, :], cmap='gray')
# plt.show()



for index, (image, label, label_name) in enumerate(train_dataset):
    
#     print(index)
    
#     plt.imshow(image[0, :, :], cmap='gray')
#     plt.show()
    
    image[image > 240.0] = 0.0

    label = label - 1.0
    
    label[label == -1.0] = 0
    
    label[label == 9.0] = 8
    
#     print(image.shape)
    
    (channel, height, width) = image.shape
    
    image = image.reshape(height, width, 1)
    
    image = np.concatenate((image, image.copy(), image.copy()), axis=2)

    
#     print(label.shape)
#     print(image.shape)
    
#     plt.imshow(label[0, :, :], cmap='gray')
#     plt.show()
    
    save_name_label = train_label_folder + '/' + label_name + '.npy'
    
    save_name_image = train_image_folder + '/' + label_name + '.jpg'
    
    np.save(save_name_label, label)
    
    imageio.imwrite(save_name_image, image)
    
#     print(image.max())
#     print(label.max())
#     print(label.min())
    
    print(np.unique(label))

Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7. 8.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 239.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 239.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7.]


Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.
Lossy conversion from float32 to uint8. Range [0.0, 240.0]. Convert image to uint8 prior to saving to suppress this warning.


[0. 1. 2. 3. 4. 5. 6. 7.]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
